### ISSUE TITLE
Support style injection target in renderer

### ISSUE THREAD

**Issue by namjul** [weserio/fela#693]
**Type**: Feature

| Packages | Version |
| -------- | ------- |
| fela     | 6.0.x   |

-------------------
#### Description

I plan on using https://github.com/seek-oss/playroom. It requires to inject the styles into iframes which have the actual relevant dom. But the actual components get executed outside of the iframe and renders the actual from into each iframe, so all styles land in the parent iframe and the child iframes don't inherit them.
styled-components supports this https://github.com/seek-oss/playroom#css-in-js-support so maybe this is also something fela could support.

#### Proposal
The renderer would need an option to tell it the target it should inject the styles.
And use it probably somewhere here: https://github.com/rofrischmann/fela/blob/master/packages/fela-dom/src/dom/connection/createNode.js#L12

**Comment by namjul** [comment]
I would provide a PR if this is something wanted.

**Comment by rofrischmann** [comment]
Hey @namjul,

As I'm going to integrate Playroom as well, I'd love to have that functionality.
I think the best way would be to add it to the fela-dom package rather than the renderer itself.
The option can be passed to the Provider in react/preact/inferno-fela as well to pass it down to the fela-dom.
That way we'd keep the agnostic renderer free of DOM specific stuff.

**Comment by weserio** [comment]
Just getting back on this issue: It looks like Playroom now uses window instead of frameWindow, so this specific issue should be resolved!
